defaults:
  - dataset: cifar10
  - optimizer: sgd
  - scheduler: cosine_anneal
  - model: resnet
  - augment: randaugment
params:
  num_epoch: 100
  batch_size: 64
  lr: 0.01
exp:
  data_dir: /dataset
  exp_name: dryrun
  checkpoint_path: checkpoint
  save_path: exp
  log_cycle: 0.1
  is_continue: False
  load_path:
  use_cuda: False
  use_amp: False
  use_lars: False
  reg_off: False
  extra_epoch: 1
  tiny_tl: False
